version: '2'

services:
  keys:
    build: "ssh"

  tweek-git:
    image: soluto/tweek-bare-repo
    volumes_from: 
      - keys
    environment:
      - PUBLIC_KEY_PATH=/gitkeys/tweekgit.pub
      - TWEEK_MANAGEMENT_URL=http://tweek-management:3000

  tweek-management:
    image: soluto/tweek-management
    depends_on:
      - tweek-git
    volumes_from: 
      - keys
    environment:
      - GIT_USER=git
      - GIT_URL=ssh://git@tweek-git/tweek/tests
      - GIT_PRIVATE_KEY_PATH=/gitkeys/tweekgit
      - GIT_PUBLIC_KEY_PATH=/gitkeys/tweekgit.pub
      - VALIDATION_URL=http://tweek-api/validation

  tweek-api:
    image: soluto/tweek-api
    ports:
      - "1111:80"
    depends_on:
      - tweek-management
    volumes_from: 
      - keys
    environment:
      - PUBLIC_KEY_PATH=/gitkeys/tweekgit_public.pfx
      - Rules__Management__Url=http://tweek-management:3000

  tests:
    build: .
    depends_on:
      - tweek-api
    environment:
      - TWEEK_LOCAL_API=http://tweek-api
