version: '2'

services:
  tweek-management:
    image: soluto/tweek-management
    environment:
      - GIT_URL
      - GIT_USER
      - GIT_PASSWORD
      - VALIDATION_URL=http://tweek-api/validation

  tweek-api:
    image: soluto/tweek-api
    ports:
      - "1111:80"
    depends_on:
      - tweek-management
    environment:
      - RulesBlob.Url=http://tweek-management:3000/ruleset/latest
